# Generated by Django 2.2 on 2020-02-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_wish_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
