# Generated by Django 2.2 on 2020-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200214_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
