# Generated by Django 2.2 on 2020-02-22 06:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_wish_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10),
        ),
    ]
